# Generated by Django 3.0.3 on 2020-04-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eddr',
            new_name='eaddr',
        ),
    ]
